baseURL = 'https://blog.dolphin0809.jp/'
languageCode = 'ja-jp'
title = 'いるかの雑記帳'
theme = 'm10c'
copyright = '&copy; since 2024 DOLPHIN0809.JP'

[params]
  author = 'Dolphin0809'
  description = 'コンピュータ、ネットワークをメインになんかいろいろ書きます。'
  avatar = 'https://secure.gravatar.com/avatar/44072195a33083fc58dcf7320e8299d6?d=identicon&s=240'
  menu_item_separator = '|'
  favicon = '/favicon.ico'

  [[params.social]]
    icon = 'brand-x'
    name = 'X'
    url = 'https://x.com/dolphin_0809_mc'
  [[params.social]]
    icon = 'brand-github'
    name = 'GitHub'
    url = 'https://github.com/Dolphin0809'
  [[params.social]]
    icon = 'brand-paypal'
    name = 'PayPal'
    url = 'https://paypal.me/dolphin0809'

  [params.style]
  darkestColor = "#161616"
  darkColor = "#333333"
  lightColor = "#d4d4d4"
  lightestColor = "#eeeeee"
  primaryColor = "#007acc"

[menu]
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
